apiVersion: v1
kind: Service
metadata:
  name: delivery-management-service # Name of the service
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: delivery-management-service
  ports:
    - protocol: TCP
      port: 80 # External port exposed to the internet
      targetPort: 8080 # The port the container is listening on
